Allow deleting subtree across multiple merges
velocidi/frise pull request #24
Opened 2021-02-19 14:43 UTC by thyandrecardoso

The previous delete behavior was not accounting for merging of multiple levels and deleting objects that are found after the first delete. This tries to correct that by specifying that once we find a delete symbol, any next merge will also see the corresponding path deleted.

2021-02-20 17:56 UTC, jcazevedo requested changes
I'm not very fond of having `DefaultMarker`s escaping the context of `DefaultsLoader`. 

Have you considered processing the includes for all `$include` directives at point before merging the resulting config with the main one? The following diff seems to pass the tests (it also removes the special handling for `$delete` markers as array elements):

```diff
diff --git a/lib/frise/defaults_loader.rb b/lib/frise/defaults_loader.rb
index 1866451..007fad5 100644
--- a/lib/frise/defaults_loader.rb
+++ b/lib/frise/defaults_loader.rb
@@ -23,30 +23,6 @@ module Frise
       @delete_sym = delete_sym
     end
 
-    # returns the config without the keys whose values are marked for removal
-    def clear_delete_markers(config)
-      case config
-      when Hash
-        config.each_with_object({}) do |(k, v), new_hash|
-          if v.instance_of?(Frise::DefaultsLoader::DeleteMarker)
-            new_hash[k] = v.value unless v.value.nil?
-          elsif v != @delete_sym
-            new_hash[k] = clear_delete_markers(v)
-          end
-        end
-      when Array
-        config.each_with_object([]) do |elem, new_arr|
-          if elem.instance_of?(Frise::DefaultsLoader::DeleteMarker)
-            new_arr.push(elem.value) unless elem.value.nil?
-          elsif elem != @delete_sym
-            new_arr.push(clear_delete_markers(elem))
-          end
-        end
-      else
-        config
-      end
-    end
-
     # rubocop:disable Lint/DuplicateBranch
     def merge_defaults_obj(config, defaults)
       config_class = widened_class(config)
@@ -61,8 +37,8 @@ module Frise
         else merge_defaults_obj({}, defaults)
         end
 
-      elsif delete_marker?(config) || delete_marker?(defaults)
-        DeleteMarker.new(@delete_sym, config)
+      elsif config == @delete_sym || defaults == @delete_sym
+        config
 
       elsif defaults_class == 'Array' && config_class == 'Array'
         defaults + config
@@ -115,34 +91,5 @@ module Frise
       return 'Integer' if %w[Fixnum Bignum].include? class_name
       class_name
     end
-
-    def delete_marker?(conf)
-      conf == @delete_sym || conf.instance_of?(Frise::DefaultsLoader::DeleteMarker)
-    end
-
-    # Keeps state once a delete symbol is found, so that we can keep deleting to the "right" while merging values.
-    class DeleteMarker
-      attr_accessor :value
-
-      def initialize(delete_sym, left)
-        @delete_sym = delete_sym
-
-        @value = if left == delete_sym
-                   nil
-                 elsif left.instance_of?(self.class)
-                   left.value
-                 else
-                   left
-                 end
-      end
-
-      def to_s
-        if @value.nil?
-          @delete_sym.to_s
-        else
-          @value.to_s
-        end
-      end
-    end
   end
 end
diff --git a/lib/frise/loader.rb b/lib/frise/loader.rb
index 7b12147..b757735 100644
--- a/lib/frise/loader.rb
+++ b/lib/frise/loader.rb
@@ -76,12 +76,14 @@ module Frise
                 rest_include_confs = include_confs[1..]
                 symbol_table = build_symbol_table(root_config, at_path, config, global_vars, include_conf)
                 included_config = Parser.parse(include_conf['file'], symbol_table)
-                config = @defaults_loader.merge_defaults_obj(config, included_config)
-                process_includes(config, at_path, merge_at(root_config, at_path, config), global_vars,
-                                 rest_include_confs)
+                processed_included_config = process_includes(included_config, at_path,
+                                                             merge_at(root_config, at_path, included_config),
+                                                             global_vars, rest_include_confs)
+                config = @defaults_loader.merge_defaults_obj(config, processed_included_config)
+                process_includes(config, at_path, merge_at(root_config, at_path, config), global_vars)
               end
             end
-      @delete_sym.nil? ? res : @defaults_loader.clear_delete_markers(res)
+      @delete_sym.nil? ? res : omit_deleted(res)
     end
 
     def process_schema_includes(schema, at_path, global_vars)
@@ -165,6 +167,17 @@ module Frise
       config.merge(head => merge_at(config[head], tail, to_merge))
     end
 
+    # returns the config without the keys whose values are @delete_sym
+    def omit_deleted(config)
+      config.each_with_object({}) do |(k, v), new_hash|
+        if v.is_a?(Hash)
+          new_hash[k] = omit_deleted(v)
+        else
+          new_hash[k] = v unless v == @delete_sym
+        end
+      end
+    end
+
     # builds the symbol table for the Liquid renderization of a file, based on:
     #   - `root_config`: the root of the whole config
     #   - `at_path`: the current path
@@ -175,11 +188,11 @@ module Frise
       extra_vars = (include_conf['vars'] || {}).transform_values { |v| root_config.dig(*v.split('.')) }
       extra_consts = include_conf['constants'] || {}
 
-      @defaults_loader.clear_delete_markers(config ? merge_at(root_config, at_path, config) : root_config)
-                      .merge(global_vars)
-                      .merge(extra_vars)
-                      .merge(extra_consts)
-                      .merge('_this' => config)
+      omit_deleted(config ? merge_at(root_config, at_path, config) : root_config)
+        .merge(global_vars)
+        .merge(extra_vars)
+        .merge(extra_consts)
+        .merge('_this' => config)
     end
 
     # builds a user-friendly string indicating a path
diff --git a/spec/frise/defaults_loader_spec.rb b/spec/frise/defaults_loader_spec.rb
index 5408774..4803a6b 100644
--- a/spec/frise/defaults_loader_spec.rb
+++ b/spec/frise/defaults_loader_spec.rb
@@ -119,18 +119,18 @@ RSpec.describe DefaultsLoader do
       'int' => '$delete',
       'bool' => '$delete',
       'arr' => '$delete',
-      'another_arr' => ['$delete'], # has no effect inside an array
       'obj' => { 'key1' => '$delete', 'key3' => '$delete' }
     }
-    loader = DefaultsLoader.new
-    conf = loader.clear_delete_markers(loader.merge_defaults(conf, fixture_path('all_types.yml')))
-    expect(conf.key?('str')).to be false
-    expect(conf.key?('int')).to be false
-    expect(conf.key?('bool')).to be false
-    expect(conf.key?('arr')).to be false
+    conf = DefaultsLoader.new.merge_defaults(conf, fixture_path('all_types.yml'))
+    expect(conf['str']).to eq '$delete'
+    expect(conf['int']).to eq '$delete'
+    expect(conf['bool']).to eq '$delete'
+    expect(conf['arr']).to eq '$delete'
     expect(conf['another_arr']).to eq(%w[elem0 elem1])
     expect(conf['obj']).to eq(
-      'key2' => 'value2'
+      'key1' => '$delete',
+      'key2' => 'value2',
+      'key3' => '$delete'
     )
   end
 end
```

2021-02-23 23:58 UTC, thyandrecardoso commented
> I'm not very fond of having DefaultMarkers escaping the context of DefaultsLoader.
>
> Have you considered processing the includes for all $include directives at point before merging the resulting config with the main one? The following diff seems to pass the tests (it also removes the special handling for $delete markers as array elements):

No. I don't think I was _seeing_ that...
That seems better, yes.

Regarding the `$delete` symbol, I have no strong opinion, I guess it is ok to let it be unhandled, but I did keep the change on the `defaults_loader_spec.rb` where we merge an array with `['$delete']`. I think it helps understand the behavior...

63a9caf should have those changes and should also address your other review comments.

2021-02-24 11:26 UTC, jcazevedo approved these changes
Looks good! Thanks! Can you just add a Changelog entry?

2021-02-24 22:41 UTC, thyandrecardoso commented
> Looks good! Thanks! Can you just add a Changelog entry?

Added in 982b547. Please take a look.

2021-02-25 01:07 UTC, jcazevedo approved these changes

2021-02-25 01:07 UTC, merged